### ISSUE TITLE
image-reflector-controller cannot recover when log truncate fails

### ISSUE THREAD

**Issue by dkerwin** [fluxcd/image-reflector-controller#105]
After a hard restart of a k8s node on my Raspberry Pi cluster the image-reflector-controller went into a crashloop and was only able to recover after the pod was deleted and recreated. The logs point to a problem with a truncate operation. I'm running v0.5.0.

```
flux-system   image-reflector-controller-774686df7b-9swbh    0/1     CrashLoopBackOff   106        23h
```

```
badger 2021/02/11 10:23:21 INFO: All 1 tables opened in 0s
badger 2021/02/11 10:23:21 INFO: Discard stats nextEmptySlot: 0
badger 2021/02/11 10:23:21 INFO: Set nextTxnTs to 872
badger 2021/02/11 10:23:21 INFO: Deleting empty file: /data/000026.vlog
badger 2021/02/11 10:23:21 ERROR: Received err: while truncating last value log file: /data/000027.vlog error: mremap size mismatch: requested: 20 got: 536870912. Cleaning up...
{"level":"error","ts":"2021-02-11T10:23:21.766Z","logger":"setup","msg":"unable to open the Badger database","error":"During db.vlog.open error: while truncating last value log file: /data/000027.vlog error: mremap size mismatch: requested: 20 got: 536870912","stacktrace":"runtime.main\n\t/usr/local/go/src/runtime/proc.go:204"}
```

**Comment by relu** [comment]
I've seen this error before (or at least a variation of it) when working on https://github.com/fluxcd/image-reflector-controller/pull/93, I thought it was just a side-effect of changing the vlog map file size and didn't really bother to investigate further. I'm no expert but it seems like this issue might be with this [mremap](https://github.com/dgraph-io/ristretto/blob/f30e50eaf8dfcde5e3968f3e055fdbcf28955d7b/z/mmap_linux.go#L39-L64) implementation and is specific to ARMv7 systems only. I'll see if I can reproduce the issue somehow but right now it kind of points towards badger (the embedded database we use) or its ristretto package and probably not something we can fix in our controller directly.

Some more information:
- Ristretto [switched to mremap from munmap + mmap](https://github.com/dgraph-io/ristretto/pull/221) on Linux because mremap is more efficient.

**Comment by kingdonb** [comment]
I have a replication of this problem, on ARMv7 raspberry pi 3b

I will set image-reflector-controller to run on the non-arm part of the cluster for now, until someone wants to work on it with me.

```
$ kff logs -f image-reflector-controller-7dccb755bb-cprhm
{"level":"error","ts":"2021-06-17T19:22:22.147Z","logger":"setup","msg":"unable to open the Badger database","error":"while opening memtables error: while opening fid: 4 error: while updating skiplist error: mremap size mismatch: requested: 20 got: 134217728"}
```

The error appears the same to me, `mremap size mismatch: requested: 20 got: ....`

My image-reflector-controller goes into crashloopbackoff as long as I have it pinned to the `kubernetes.io/arch=arm` label

**Comment by kingdonb** [comment]
With the new Flux release, `v0.15.1`, I cannot seem to replicate it anymore 👍 🎉

**Comment by kingdonb** [comment]
I understand what's happening now, and I'm adding an FAQ entry to document this

The badger database is where image tag information is kept. As I understand it, Flux collects all the data that image-reflector-controller gathers and stores it in there. I guess the database is not fully transactional, or the way that it is used is not ACID. If your database is truncated because your cluster node ran out of memory and it was killed off in the middle of some operation, you will experience this issue. I have not researched the details but I was able to work around it by adding enough swap.

I have two Raspberry Pi 2b and 3b nodes with storage between 8GB and 32GB. Both are running Raspbian Lite at the latest version. I was able to allocate a 2GB swap file on each and this condition is resolved. This seems to indicate that it's a low-memory condition, not necessarily an arm32-specific issue (but only ARM users are operating in such low memory conditions, where this trouble is likely.)

On Raspbian based on Debian 10, systemd is of course in use, and you cannot just add a swap file in fstab, (error messages at least indicated one should not, since swap files are not devices, I don't understand why exactly but it is counterindicated.)

The correct way to add a swap is apparently now with dphys-swapfile, configured in `/etc/dphys-swapfile`

```
# set size to absolute value, leaving empty (default) then uses computed value
#   you most likely don't want this, unless you have an special disk situation
CONF_SWAPSIZE=4096
```

Give this a setting larger than 100, (there are other factors that wound up limiting mine to 2000 MB) then run to initialize:

```
$ sudo dphys-swapfile setup
$ sudo dphys-swapfile swapon
```

I will find some raspberry pi or raspbian documentation that supports this, and add it to the FAQ. Looking at creating a new section "Raspberry Pi Questions" in the FAQ, since I am not sure where else to put this information.
