### ISSUE TITLE
unable to find docker auth in secret

### ISSUE THREAD

**Issue by HarryGogonis** [fluxcd/image-reflector-controller#124]
The ImageRepository uses `ref.Context().RegistryStr()` to get the container registry auth from the map in the secret
https://github.com/fluxcd/image-reflector-controller/blob/e164cfc676cebc0b509cc888dfd3b84964e03d54/controllers/imagerepository_controller.go#L193
https://github.com/fluxcd/image-reflector-controller/blob/e164cfc676cebc0b509cc888dfd3b84964e03d54/controllers/imagerepository_controller.go#L368

For docker, this value is `index.docker.io`. Unfortunately, many .dockerconfigjson contain the full domain `https://index.docker.io/v2` as [shown in the k8s docs](https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/)

I can change my docker secret for now, but it might be a "gotcha" for other users

**Comment by squaremo** [comment]
Hmm yeah, we had to deal with this in Flux v1 too. The way [it is done there](https://github.com/fluxcd/flux/blob/master/pkg/registry/credentials.go#L71) is to parse each map key from `auths`  as though it's a URL, and use only the hostname. There's a bit of fiddliness since the map key might _not_ be a URL, but it works well enough.
