### ISSUE TITLE
Authentication failure with ECR

### ISSUE THREAD

**Issue by davisford** [fluxcd/image-reflector-controller#139]
The image reflector controller log is showing this:

```
{"level":"error","ts":"2021-04-27T14:55:40.005Z","logger":"controller-runtime.manager.controller.imagerepository","msg":"Reconciler error","reconciler group":"image.toolkit.fluxcd.io","reconciler kind":"ImageRepository","name":"giftcard","namespace":"flux-system","error":"GET https://XXXXXXXXX.dkr.ecr.us-east-1.amazonaws.com/v2/redacted/redacted/tags/list?n=1000: unexpected status code 401 Unauthorized: Not Authorized\n"}
```

Which is bizarre because the node in EKS has this policy attached to it:

```json
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": [
                "ecr:GetAuthorizationToken",
                "ecr:BatchCheckLayerAvailability",
                "ecr:GetDownloadUrlForLayer",
                "ecr:GetRepositoryPolicy",
                "ecr:DescribeRepositories",
                "ecr:ListImages",
                "ecr:DescribeImages",
                "ecr:BatchGetImage",
                "ecr:GetLifecyclePolicy",
                "ecr:GetLifecyclePolicyPreview",
                "ecr:ListTagsForResource",
                "ecr:DescribeImageScanFindings"
            ],
            "Resource": "*"
        }
    ]
}
```

...and if I specify an image tag for the same repository, Kubernetes has no problem at all pulling the image.

I understand there is a mechanism you recommend to setup a secret + daemon set to get the credentials, but I'm puzzled as to why it can't just pull the image when the node itself has permissions to do so, and Kubernetes pulls the images just fine.

**Comment by relu** [comment]
Hello @davisford, thanks for submitting the issue.

I think your question is a valid one and I hope that you'll find my answer useful.
The node itself does not have permissions to pull images from ECR, rather it has permissions to authenticate against ECR. In the situation of EKS, [Kubelet](https://github.com/kubernetes/kubelet) (the daemon service running on the node) is configured to use the [AWS ECR credentials provider](https://v1-20.docs.kubernetes.io/docs/tasks/kubelet-credential-provider/kubelet-credential-provider/#configure-a-kubelet-credential-provider). We do not have access to the credentials cached by Kubelet so this is the reason why we [need our own credentials](https://fluxcd.io/docs/guides/image-update/#aws-elastic-container-registry) to access the ECR registry API.

**Comment by MartinEmrich** [comment]
Hi!
I am trying to replace flux v1 with flux v2, and stumbled upon the same issue. 

But I am curious what's the difference here... Flux v1 is able to detect new images in the ECR and update the deployments automatically, and indeed the flux SystemAccount there has not even any IAM resources attached. So it has to work with kubernetes means alone, or the standard AWS EKS policies attached to the nodes.

What does flux v1 do differently, and can I do/use that for flux v2, too?

**Comment by MartinEmrich** [comment]
I checked to make sure: all our (perfectly working) flux v1 deployments have only a normal serviceccount without AWS IAM permissions. So any IAM permissions flux may have are those assigned to the nodes themselves, which do not relate to the Kubernetes serviceAccount. So I guess flux v1 does access the ECR just like any other container registry.
The only AWS specialty is logging in to the ECR (the "docker login" command), which uses AWS IAM (e.g. `aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin XXXXXXXXX.dkr.ecr.us-east-1.amazonaws.com`)
(that works even without a kubernetes service account)

The node IAM role has sufficient privileges for docker access to the ECR (Thats what also kubelet uses to pull the images, too). so that's what flux v1 also seems to do.
(Somewhere around here): https://github.com/fluxcd/flux/blob/master/pkg/registry/aws.go#L286

So neither flux v1 nor flux v2 need an IAM service account.

I see no reason not to do the same in flux v2, the image-reflector-controller has never more privileges than any other process on the cluster, just as flux v1. IMHO any administrator actually enriching the flux serviceAccout with additional IAM privileges should actually now what he's doing. (the default AWS EKS policies grant read-only access to all ECRs anyways)

**Comment by squaremo** [comment]
> I checked to make sure: all our (perfectly working) flux v1 deployments have only a normal serviceccount without AWS IAM permissions. So any IAM permissions flux may have are those assigned to the nodes themselves, which do not relate to the Kubernetes serviceAccount.

OK, that's me not fully understanding how AWS IAM works with Kubernetes 😳  It looks like having the role assigned to either of the node or the service account is adequate.

The point is that it is a permission given to the controller, rather than to individual objects in the API. Once you grant it to the controller, any user of the cluster with the ability to create `ImageRepository`/`ImagePolicy` objects can get information from any ECR repository to which the IAM role has access, and that breaks the expectation that access is granted per object.

You could make the argument that breaking that expectation (subject to a flag!) is worth it in some circumstances*, for the convenience of not having to create a `CronJob` everywhere you want to have credentials.

(*I am thinking in particular of clusters in which every user is fully trusted)

**Comment by MartinEmrich** [comment]
That's my point: the permission is neither granted to the controller nor to individual resources, but to the whole EKS cluster by default.
So the fluxv2 implementation actually breaks the expectation (held up by both EKS convention itself and fluxv1), that working with the ECR in the same account and region "just works".

That's just "how AWS EKS and ECR rolls". The IAM policy to access the ECR service is "granted" to all nodes in the cluster when you create a new EKS cluster automatically (https://console.aws.amazon.com/iam/home?region=us-east-1#/policies/arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly$jsonEditor (needs a valid AWS login)). So at no point here a user explicitly grants permissions to a controller or other CR.

All AWS services (with a few rare exeptions) use their IAM service for AAA, so they (IMHO) even shoehorned their Container Registry docker api into it (that's where the 12h timeout comes from, with your IAM authorization, you get a temporary docker password for the docker API part of ECR)

So IMHO there's no security implication. Indeed access control to ECR repositories is done via Image Pull Policies (where you can e.g. grant access to clients in other AWS accounts/regions).

Of course, one can grant additional IAM permissions via a multitude of mechanics (IAM node role, IAM service account, or even configuring access keys manually via environment variables), and all official AWS SDKs will automatically try each until it gets a valid identity. So your argument would have been valid in any other case, but when it comes to pulling/accessing the container registry, all of the EKS cluster already has read access to "*".

**Comment by relu** [comment]
> So the fluxv2 implementation actually breaks the expectation (held up by both EKS convention itself and fluxv1), that working with the ECR in the same account and region "just works".

That is fair, however, note that the current implementation was delimited from the responsibility to obtain a container registry authentication token, and this, as far as I know, was a conscious decision. What I mean is that instead of relying on specific, non-standard implementations to obtain the auth tokens (be it for ECR, GCR, or ACR) implemented at the level of the controller, we leave that to the user and just expect a secret containing the OCI registry credentials (which is standardized).

The argument that the EKS-backed clusters already have access to ECR and the expectation that anything running inside it should have the same are valid, but it misses the point. As I mentioned in my previous comment, it represents only "access to obtain an authentication token", you still need to implement the logic to do so and this logic does not exist in the controller at the moment (it never touches the AWS ECR API).

To be clear, I'm not necessarily against a provider-specific authentication mechanism being implemented at the level of the controller (as Flux v1 had), but I think the discussion boils down to some philosophical arguments around the controller's responsibilities in terms of integrating or not with the various cloud provider OCI registries.
Personally, I find the solution of [using a CronJob resource](https://fluxcd.io/docs/guides/image-update/#aws-elastic-container-registry) to manage obtaining and storing the authentication token for ECR into a secret trivial and acceptable.

**Comment by MartinEmrich** [comment]
Hmm, the mentioned CronJob seems to be a crude workaround, until more than one ECR is being used, and/or it is not previously known.

If it was configurable to have multiple secrets, to be on par with fluxv1, the cronjob would have to somehow scan every ImageRepository resource cluster-wide, extract all used ECRs, log in to each ECR to get a token, and store each token in a way that image-reflector-controller can find the right token for the right ECR. And all that triggered by each Git commit, as each commit might introduce a new, previously unused ECR, where no token is yet pulled and cached. 
This would probably be an additional running service, integrated via events and APIs.

Now I not only have to maintain a set of ImageRepository resources, but also a set of matching secrets and cron jobs, and have to trigger them manually in advance if the secret is not yet present (which might happen often during tests where the whole cluster is torn down and built up repeatedly).

If it is your conscious design decision to keep vendor-specific code out of flux v2, I would have to accept that....
I also understand your arguments, and the fact that flux v2 is not yet on-par with flux v1 feature-wise.

It's just sad for existing flux users wanting to upgrade, for us this means we have to do things differently. (i.e. not using image automation anymore, but rather manually updating version tags in git).

I plan to try and "cut&paste" the relevant code from flux v1 into image-reflector-controller, but my Go skills are not really good... If I get it "go"ing (SCNR), it might make a PR...

**Comment by squaremo** [comment]
@MartinEmrich Thank you for putting time into discussing this, and for considering putting a PR together.

The hurdle here is not so much that no-one has ported the code over, or keeping vendor-specific code out, it's that the system works in a different way.

Flux (v1) basically assumes it has full control over the cluster, and that you want to know the tags for every image mentioned in the cluster, so it chases down all image pull secrets and gets platform-specific tokens behind the scenes, and effectively makes all the information it finds available to every process in the cluster.

But the new controllers do not start with these assumptions. In particular, they do not assume you want them to pass on the authority to which they have access (e.g., platform auth APIs), to tenants of the cluster. To be able to scan an image repo, you have to prove you have permissions to do so, by supplying a secret.

With that in mind, may I attempt gently to redirect your energy ... If you can come up with a design in which it's safe for the controller to pass on ambient authority, we can discuss how to implement it. "Safe" could mean there's some other way of tenants proving they have access to ECR (etc), or it could mean that an administrator explicitly grants access to all tenants.

**Comment by MartinEmrich** [comment]
@squaremo thanks for bearing with me! (Reading my last post a day later, it might come across a bit "ranty", in that case I apologize...)

Indeed i find it hard to come up with a scenario where having a cluster-wide controller with flux-v1-style behaviour would allow any "privilege escalation"... After all, the cluster must only operate with the IAM privileges it has been given by the administrator. The only way to circumvent that would be to store AWS IAM access keys and secrets in the Control Plane (ConfigMaps/Secrets) or in the user plane (within an application). And that violates one of the most fundamental IAM best practices, to never ever store IAM credentials in your system.

But I am just a chap with a google, and we only ever deploy EKS clusters here in a way that only a single trusted entity (i.e. our company) has access to it, so I might miss the perspective of a true multi-tenant kubernetes cluster.
Basically, if there's a GitRepository/Kustomization pair to a git repository of an untrusted party, that party could gain effectively the same AWS IAM privileges as the controller itself (or the cluster node) just by running a pod and using any of the official AWS SDKs or CLI, regardless of the namespace.
I cannot think of a way how a tenant (I guess you mean a partially trusted additional user of the EKS cluster) could actually bring additional access to the ECR, as the cluster already has full access.

But long story short, I would consider a simple "safe" way by adding the needed functionality to the controller, but disabling it by default. So if one runs on AWS EKS, one can (consciously) pass an environment variable or command line option to the image-reflector-controller to enable the access to ECR.
Getting more creative.... One step further could be a (cluster-global, admin-managed) ACL-like configuration which might map "allowed" ECR (or, in general, container registry URL) regex patterns to "privleged" namespaces or namespace/ImageRepository pairs... (As I have a single-tenant cluster, I would just insert something like "*:*", but the users you refer to might model more complex privileges there.
Of course these tenants could still run any image from any ECR that grants access to this AWS account, just the image-reflector-controller would refuse to scan certain repositories.
That might also need input from Google/Azure experts to cater to their specialties...
