### ISSUE TITLE
Container registry auth not found in secret

### ISSUE THREAD

**Issue by from-nibly** [fluxcd/image-reflector-controller#99]
I created an image repository with a `spec.image` of `ghcr.io/<org>/<image-name>` . I added a secret ref of `spec.secretRef.name` with the value of `github` there is a github secret in the flux-system namespace that has auth that is identical to the one kubernetes is using to download container images but I am getting an error of 

```
"auth for \"ghcr.io\" not found in secret flux-system/github"
```

Any ideas what could be causing this? I am using the new github container image repositories to host my container images.

**Comment by from-nibly** [comment]
here is the base64 decoded version of the secret (redacted of course)


```json
{"auths":{"https://ghcr.io":{"username":"xxxxxxx","password":"xxxxxx","auth":"xxxxxxx"}}}
```

and here is the entire command I ran (also redacted)

```bash
kubectl create secret -o yaml -n flux-system docker-registry github --dry-run --docker-server=https://ghcr.io --docker-username=xxxxxx --docker-password=xxxxxxx |  kubeseal --format=yaml --controller-name=kubeseal-sealed-secrets --controller-namespace=kubeseal --context=monol > ./clusters/local/flux-system/docker-secret.yaml
```

I'm realizing I might need to try without the schema in the server? for some reason this works just fine to help kubernetes download docker containers.

**Comment by from-nibly** [comment]
OK I think that got me farther. It looks like the issue now is this error on the image-automation-controller.  `unknown error: ERROR: The key you are authenticating with has been marked as read only.`  I believe that is github responding to a request that the pod is making. Is it using the ssh key from bootstrapping? How would it get access to the repo through a read only key when the github PAT used to bootstrap had full repo permissions? It's possbile that I initially bootstraped the cluster with a read only PAT but I've since rebootstrapped with a new PAT that has full repo permissions.

**Comment by relu** [comment]
@from-nibly did you happen to bootstrap flux using `--token-auth`? Otherwise, flux will create a deploy key in your git repository settings which is read-only by default. You can check this under `https://github.com/<org>/<repo>/settings/keys`. You can read about that in the [docs](https://toolkit.fluxcd.io/guides/installation/#github-and-github-enterprise). As you can see [in the guide](https://toolkit.fluxcd.io/guides/image-update/#install-flux), the example there uses `--token-auth`.

If you do use a deploy key and it is read-only you will not be able to convert it to a read-write key, instead, you will have to delete and re-create the key, the value of which you can get from the secret flux created during bootstrap.

**Comment by from-nibly** [comment]
Oh wow. I don't know how I didn't see that! Everything is working after re-bootstrapping.

Thank you for your help!

**Comment by squaremo** [comment]
Sounds like you are good to go @from-nibly -- I'll close this issue. For posterity, here's some detailed instructions on how to replace the read-only git secret at https://toolkit.fluxcd.io/guides/flux-v1-automation-migration/#replacing-the-git-credentials-secret.
